### ISSUE TITLE
"The redirect_uri URL must be absolute"

### ISSUE THREAD

**Issue by jthemphill** [bakert/tournament#1]
I assume you didn't program this on a laptop? I get this error after clicking the "Sign in" button from while my server is listed as localhost:8000.

**Comment by bakert** [comment]
I did, in fact, program it on a laptop :D

There's a typo in config.json.example that has the hostname as "/localhost" instead of "localhost". I wonder if that's the problem you are seeing. I've fixed it but your config.json will need to be altered if that's the problem.

Can you let me know if that was it?

**Comment by jthemphill** [comment]
Yup, thanks!
